apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::717448285858:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UIVBLXREMS7O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::717448285858:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-05T17:33:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1664"
  uid: 8d211207-e21e-4d01-b2d4-7167e1f6518d
